### ISSUE TITLE
Non-descriptive errors when parsing YAML

### ISSUE THREAD

**Issue by nizarmah** [nizarmah/laced#24]
### Description

If there's a mistake in the YAML, it results in weird errors.

For example:
```yaml
tests:
  methodName:
    description: ...
    cases:
      - description: ...
        calls:
          method:
            with:
              - []
          defines:  # this is should be aligned with "calls" not "method"
            variable:
              with:
                - "something"
```

Provide a better error message to help the user identify it.
