### ISSUE TITLE
Connect unit tests so they act together

### ISSUE THREAD

**Issue by nizarmah** [nizarmah/laced#25]
### Description

The unit tests need to act together so we can easily identify issues in the future.

This is a very important feature.

The initial implementation should be prototype-y. 
But it still should provide value.

We'll approach this by ensuring a method is called with the expected input.

Let's say we have the following code:

```typescript
function foo(x: string) {
    console.log("bar: ", bar(x))
}

function bar(x: string) {
    return x.split("").reverse().join("")
}
```

We also have the following tests:

```yaml
tests:
  foo:
    description: Logs result of bar
    cases:
      - description: calls bar
        parameters:
          - "hello"
        calls:
          - bar:
            with:
              - "hello"

  bar:
    description: Reverses string
    cases:
      - description: Returns reversed string
        parameters:
          - "test"
        returns: "tset"
```

In the example above, bar is tested with `test` but not `hello`.
Yet, foo calls bar with `hello`. 

In this case, we should check if bar has a test that takes the input `hello` which foo called `bar` with.
We don't care that bar tests `test` as well. But we want to be sure that bar is testing `hello` as well.

And that's how we'll initially connect unit tests so that they act together.

From there, we can build on top of that or even replace it when we find a better solution.
